apiVersion: v1
kind: Service
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  type: ExternalName
  externalName: host.minikube.internal
  ports:
  - port: 12201
    targetPort: 12201
    protocol: UDP
    name: gelf




