spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/auth_db
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  session:
    store-type: redis
    redis:
      namespace: spring:session

logging:
  level:
    org.springframework.security: DEBUG

