apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.scrapeInterval }}
      evaluation_interval: {{ .Values.evaluationInterval }}

    scrape_configs:
      - job_name: 'postgresql-auth-db'
        static_configs:
          - targets: ['auth-db-postgresql-0.auth-db-postgresql:9187']
            labels:
              database: 'auth_db'
              service: 'auth-service'

      - job_name: 'postgresql-product-db'
        static_configs:
          - targets: ['product-db-postgresql-0.product-db-postgresql:9187']
            labels:
              database: 'product_db'
              service: 'product-service'

      - job_name: 'postgresql-customer-db'
        static_configs:
          - targets: ['customer-db-postgresql-0.customer-db-postgresql:9187']
            labels:
              database: 'customer_db'
              service: 'customer-service'

      - job_name: 'postgresql-order-db'
        static_configs:
          - targets: ['order-db-postgresql-0.order-db-postgresql:9187']
            labels:
              database: 'order_db'
              service: 'order-service'

      - job_name: 'spring-boot-services'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - shop-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

