apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-service.fullname" . }}-config
  labels:
    app: {{ include "customer-service.name" . }}
data:
  application.yml: |
{{ tpl (.Files.Get "config/application.yml") . | indent 4 }}
  customer-service.yml: |
{{ tpl (.Files.Get "config/customer-service.yml") . | indent 4 }}

