apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  metrics-username: {{ .Values.auth.metricsUser | b64enc | quote }}
  metrics-password: {{ .Values.auth.metricsPassword | b64enc | quote }}

