apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    app: {{ include "auth-service.name" . }}
    chart: {{ include "auth-service.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}

