spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/auth_db
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  session:
    store-type: redis
    redis:
      namespace: spring:session
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080/auth

app:
  oauth2:
    redirect-uri: http://localhost:3001/test-oauth2.html

logging:
  level:
    org.springframework.security: DEBUG

