apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-service.fullname" . }}-config
  labels:
    app: {{ include "product-service.name" . }}
data:
  application.yml: |
{{ tpl (.Files.Get "config/application.yml") . | indent 4 }}
  product-service.yml: |
{{ tpl (.Files.Get "config/product-service.yml") . | indent 4 }}

