apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-service.fullname" . }}
  labels:
    app: {{ include "product-service.name" . }}
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}

