global:
  storageClass: standard
  imagePullPolicy: IfNotPresent

auth-service:
  enabled: true
  replicaCount: 1

product-service:
  enabled: true
  replicaCount: 1

customer-service:
  enabled: true
  replicaCount: 1

order-service:
  enabled: true
  replicaCount: 1

postgresql:
  enabled: true

redis:
  enabled: true

kafka:
  enabled: true

krakend:
  enabled: true

graylog:
  enabled: true

jaeger:
  enabled: true

prometheus:
  enabled: true

grafana:
  enabled: true

