apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}-config
  labels:
    app: {{ include "order-service.name" . }}
data:
  application.yml: |
{{ tpl (.Files.Get "config/application.yml") . | indent 4 }}
  order-service.yml: |
{{ tpl (.Files.Get "config/order-service.yml") . | indent 4 }}

